services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=developer
    volumes:
      - .:/home/developer/host_dir
      - /tmp/.X11-unix/:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - HOSTIP=${HOSTIP}
    network_mode: "host"
    privileged: true
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
